# Generated by Django 5.0 on 2024-02-29 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name1', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Название 1')),
                ('org_name2', models.CharField(blank=True, default='', max_length=1000, verbose_name='Название 2')),
                ('org_name3', models.CharField(blank=True, default='', max_length=1000, verbose_name='Название 3')),
                ('mainnew', models.TextField(blank=True, default='', null=True, verbose_name='Адрес')),
                ('address_comment', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Комментарий')),
                ('contact_groups_contacts1_text1', models.CharField(blank=True, default='', max_length=1000, verbose_name='Контакт')),
                ('contact_groups_contacts1_text2', models.CharField(blank=True, default='', max_length=1000, verbose_name='Контакт')),
                ('contact_groups_contacts1_text3', models.CharField(blank=True, default='', max_length=1000, verbose_name='Контакт')),
                ('contact_groups_contacts2_text1', models.CharField(blank=True, default='', max_length=1000, verbose_name='Контакт')),
                ('contact_groups_contacts2_text2', models.CharField(blank=True, default='', max_length=1000, verbose_name='Контакт')),
                ('contact_groups_contacts2_text3', models.CharField(blank=True, default='', max_length=1000, verbose_name='Контакт')),
                ('ads_article', models.CharField(blank=True, default='', max_length=3000, verbose_name='Инфо')),
                ('article_warning', models.CharField(blank=True, default='', max_length=1000, verbose_name='Доп инфо')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('visible', models.BooleanField(default=True, null=True, verbose_name='Отображать')),
                ('pro', models.BooleanField(default=False, null=True, verbose_name='PRO')),
                ('slug', models.SlugField(allow_unicode=True, max_length=1000, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rubrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_original', models.CharField(blank=True, default='', null=True, verbose_name='Рубрика')),
                ('visible', models.BooleanField(default=False, verbose_name='Отображать')),
                ('slug', models.SlugField(allow_unicode=True, max_length=1000, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Anonymous', max_length=300)),
                ('content', models.TextField()),
                ('is_positive', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='catalog.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyRubrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.company')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.rubrics')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='rubrics',
            field=models.ManyToManyField(blank=True, to='catalog.rubrics'),
        ),
    ]
