# Generated by Django 3.2.24 on 2024-03-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubrics',
            name='name_original',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Рубрика'),
        ),
    ]
